### PR TITLE
Safemode bug fixed

### PR DESCRIPTION
**Pull request by Nikekson**
This change is [Reviewable](https://reviewable.io/reviews/xmoto/xmoto/6)

### CODE REVIEW

**Comment by InfinityMin3r** [comment]
Why is there a large commented block as opposed to simply deleting it?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/6#-:-KiMSKDHoYqoeFmrIpp_:b-ase5hd)*

**Comment by Nikekson** [comment]
I left it there when fixing the issue, didn't clean it up afterwards for whatever reason.

**Comment by InfinityMin3r** [comment]
> 
Also, for state scene, I see a lot of empty lines, are those supposed to be there?

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/6#-:-KiMSur4lqR0f0q8HdzH:by68wi2)*

**Comment by Nikekson** [comment]
Where exactly?

**Comment by InfinityMin3r** [comment]
OK (I made a mistake when  looking at the diff. This is good!

---

Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/6#-:-KiMTOV4Lkwqmxuoruvo:b-4vn5c0)*

**Pull request merged**
