### PR TITLE
Switch to CMake from Autotools

### PR DESCRIPTION
**Pull request by bb010g**
~**NOTE:** This is just for gathering comments currently. It doesn't have full i18n yet or cross-platform testing, so we really shouldn't merge it.~

Current workflow I've been using to iterate on my Arch box:
```bash
# Set up clean build dir
mkdir build
cd $_
cmake -G Ninja \ # 'cmake -h' lists available generators
-D LUA_INCLUDE_DIR=/usr/include/lua5.1 \ # will vary by OS, may not be necessary
-D CMAKE_INSTALL_PREFIX=/tmp/xmtest \ # avoids my normal install
-Werror=dev \ # CMake warnings are errors; doesn't affect build
..

ninja xmoto # build source
ninja xmoto_pack # pack xmoto.bin, needs built binary
ninja install # can probably be replaced with a CPack command
XDG_DATA_DIRS=/tmp/xmtest/share/ /tmp/xmtest/bin/xmoto # semi-isolated run
```

Major changes:
* Restructured `src` to fit the groups specified in the Autotools scripts (these can be shuffled around after this PR if organization is poor)
* Faster building through Ninja or other CMake generators (`ninja xmoto` with Ninja takes ~30 seconds while Make takes ~2 minutes on my laptop)
* Much saner build files
* Better tooling support in the future (e.g. clang-tidy)
* Slimmed down the Gettext workflow & brought it closer to standards
* C++11 required
* Lua 5.1 now vendored
* Vendored libraries used more aggressively if not detected

Minor changes:
* `.gitignore` added
* Better XDG support (`XDG_DATA_DIRS` is now respected) (probably should update our in-tree copy soon)
* Started standardizing header include format (finish in a later PR)
* Changed Lua detection a bit (should be about as reliable)
* Deterministic build (no more compile datetime in binary)

Untested/unfinished:
* [x] Internationalization (needs fixes & testing)
* [x] Cross compilation (using MXE works hackily at the moment)
* [ ] MinGW generator (MSYS)
* [ ] Visual Studio generator
* [ ] Xcode generator

If anyone can test and/or review this, it would be greatly appreciated. I've only got so much time, and not many machines. :)

---
This change is [Reviewable](https://reviewable.io/reviews/xmoto/xmoto/8)

### CODE REVIEW

**Comment by Nikekson** [comment]
I absolutely love this! After fiddling with a couple of things, it worked like charm... Except for one thing.
I had to copy `Textures/Fonts/DejaVuSans.tff` and `Textures/Fonts/DejaVuSansMono.ttf` from the bin directory to /usr/share/xmoto for the game to run

**Comment by bb010g** [comment]
That font bit is strange. The `DRAW_FONT_FILE` constants are set to `Textures/Fonts/` paths. As for the C++11 bit, I'm not actually sure what are code standards are at the moment, so I've just knocked it back to C++98 and noted it in the build config. What command were you testing with?

**Comment by Nikekson** [comment]
If you mean the command for enabling c++11 support, I used:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`
Also, I forgot to mention that I also had to copy `xmoto.bin` to the same directory as the font files.

**Comment by bb010g** [comment]
No, not the C++11 bit. What command are you testing XMoto with? You shouldn't have to be copying these into /usr/share.

**Comment by Nikekson** [comment]
Oh, exactly what you provided at the beginning of your initial comment. I also tried to fiddle around with `XDG_DATA_DIRS`, with no luck however.

**Comment by bb010g** [comment]
Are you `make` or `ninja install`ing it? That should take care of putting all that stuff there.

**Comment by Nikekson** [comment]
`ninja install`

**Comment by bb010g** [comment]
This would probably be easier to figure out on Discord.

**Comment by Nikekson** [comment]
Yeah, let's switch there

**Comment by bb010g** [comment]
Turns out I forgot that `XDG_DATA_DIRS` needs a `share/` at the end when typing this up. Edited my example.

**Comment by bb010g** [comment]
Copied from the commit message because I'm lazy and it's late:

Mostly finish i18n. I swear I'm going mad.

I can't, for the life of me, figure out how to make the smegging
language selector work. I can set LANG=whatever just fine from the
command line, but I can't get the selector to affect it in-game. I'm
just pushing now because this is taking far too long.

**Comment by bb010g** [comment]
Ok. I think this is at a state where merging wouldn't kill everyone's groove, and having it be in `master` would be good to stabilize everything and figure out a good Windows workflow.

**Comment by Nikekson** [comment]
:lgtm:

---

Reviewed 401 of 402 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
Review status: 389 of 869 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/8#-:-Kjc_XshWhXPZCzm6Hkk:bnfp4nl)*

**Comment by InfinityMin3r** [comment]
:lgtm:

---

Review status: 282 of 876 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/8#-:-KjuFXz8kuWSgTP_BGOk:bnfp4nl)*

**Comment by InfinityMin3r** [comment]
Reviewed 377 of 402 files at r1, 1 of 1 files at r2, 3 of 6 files at r3, 9 of 13 files at r4, 138 of 143 files at r5, 145 of 333 files at r6, 362 of 492 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/8)*

**Comment by Nikekson** [comment]
Reviewed 12 of 402 files at r1, 13 of 13 files at r4, 143 of 143 files at r5, 333 of 333 files at r6, 492 of 492 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/8)*

**Pull request merged**
