### PR TITLE
Run clang-format over src

### PR DESCRIPTION
**Pull request by bb010g**
The easiest way to make sure this works well would probably be to do a file-by-file review of all of this on Reviewable. `xmoto/glext.h` wasn't touched.

I tried to keep the style relatively similar to what we used in a lot of the codebase, but we just didn't have standards for a lot of things.

Pinging @Nikekson as he was talking about doing some formatting stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/xmoto/xmoto/12)

### CODE REVIEW

**Comment by Nikekson** [comment]
Reviewed 367 of 367 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/12)*

**Comment by Nikekson** [comment]
This is weird. I grabbed a fresh clone of the branch, tried building, and it failed. I could have sworn it built fine yesterday when I initially tested it..  Anyway, there are some missing `#include`'s, `UserConfig.h` needs to include <string> and `<vector>`, and `XMotoLoadLevelsInterface.h` `<string>`

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/12#-:-KliRj2InH2Lnw8Qq5jr:bupwfqk)*

**Comment by bb010g** [comment]
Fixed the includes. I really just need to run include-what-you-use over this soon.

---

Review status: 358 of 360 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/12#-:-Kljo75kYvnGU2P5pJh9:bpusfmd)*

**Comment by Nikekson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xmoto/xmoto/12)*

**Pull request merged**
