### PR TITLE
Safemode bug fix

### PR DESCRIPTION
**Pull request by Nikekson**
This change is [Reviewable](https://reviewable.io/reviews/xmoto/xmoto/4)

### CODE REVIEW

**Comment by bb010g** [comment]
Could you rebase this off of the latest master?

**Comment by bb010g** [comment]
Wait, what? Why are you merging from here _into yourself_?

**Comment by Nikekson** [comment]
How so?

**Comment by bb010g** [comment]
Sorry, I can't read. Anyhow, you're merging from your branch into xmoto's new `safemode_fix` branch, which doesn't do much. I'm not sure why you switched off of `master`. You don't need a PR for what you're doing.

**Comment by Nikekson** [comment]
I will re-commit, to master this time, and close this.

**Comment by bb010g** [comment]
What? You can't commit directly to master.

**Comment by Nikekson** [comment]
Oh, yeah... Derp :smile:

**Pull request closed without merging**
