### PR TITLE
Fix memory leak at exit

### PR DESCRIPTION
**Pull request by BeWorld2018**
Add SDL_DestroyWindow after delete GL context

### CODE REVIEW

**Comment by villelahdenvuo** [comment]
It doesn't look like this function is called from anywhere. Also doesn't the OS free all the memory of the process on exit anyway?

**Comment by Nikekson** [comment]
> It doesn't look like this function is called from anywhere. Also doesn't the OS free all the memory of the process on exit anyway?

It's called in `GameApp::run_unload()`:
https://github.com/xmoto/xmoto/blob/9bf4ad4446b18ef10198be5bdc675a5085dd8f0a/src/xmoto/GameInit.cpp#L1048

**Comment by Nikekson** [comment]
@BeWorld2018 looks good, but please use 2 spaces instead of tabs

**Comment by villelahdenvuo** [comment]
Looks like Github search is still not perfect. 😄

**Pull request merged**
