### PR TITLE
CMake: Fix libpng version mismatch on macOS

### LINKED ISSUE #193: Broken macOS build from source
When building from source on macOS for arm64 arch, it opens and immediately closes. Launching it from console, it says:
```
fatal exception : invalid or missing texture file (Textures/UI/Misc.png)
```
This is the verbose and debug output:
```
LANGUAGE=
Wanted resolution: 800x600
GL: Apple M1 Pro (Apple)
GL: using ARB_vertex_buffer_object
GL: using EXT_framebuffer_object
GL: using ARB_fragment_shader/ARB_vertex_shader/ARB_shader_objects
Resolution: 800x600
XmDb version is 37
Joystick mappings loaded
0 compatible controllers found
** Debug ** : Controller mappings:
Loading theme from file Themes/original.xml
** Warning ** : Edge with no scale
Using theme: Classic
** Warning ** : TextureManager::loadTexture() : texture 'Textures/UI/Misc.png' not found or invalid
UserUnload started at 0.266
net: number of TCP packets sent      : 0
net: biggest TCP packet sent         : 0 bytes
net: size of TCP packets sent        : 0 bytes
net: number of UDP packets sent      : 0
net: biggest UDP packet sent         : 0 bytes
net: size of UDP packets sent        : 0 bytes
net: number of TCP packets received  : 0
net: biggest TCP packet received     : 0 bytes
net: size of TCP packets received    : 0 bytes
net: number of UDP packets received  : 0
net: biggest UDP packet received     : 0 bytes
net: size of UDP packets received    : 0 bytes
** Debug ** : Open db for thread with key 'XMTHREADSTATS'
** Warning ** : sendAsynchronousMessage message [[STATS_UPDATED]s] sent and there's no state to receive it.
** Debug ** : UserUnload saveConfig at 0.351
** Debug ** : UserUnload saveConfig ended at 0.353
** Debug ** : ---Texture not freed automatically---
** Debug ** : --- --- ---
UserUnload ended at 0.357
fatal exception : invalid or missing texture file (Textures/UI/Misc.png)
```

### PR DESCRIPTION
**Pull request by nikekson**
Fixes #193

### CODE REVIEW

**Comment by caco-underscore** [comment]
With this commit, now it segfaults. Before opening lldb, I notice that the bundle now contains libraries for multiple architectures instead of the single 'Mach-O 64-bit dynamically linked shared library arm64'. It also contains 47 files instead of 38.
Before:
```
libFLAC.12.dylib:          Mach-O 64-bit dynamically linked shared library arm64
libSDL2-2.0.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libSDL2_mixer-2.0.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
libSDL2_net-2.0.0.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libSDL2_ttf-2.0.0.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libfluidsynth.3.3.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
libfluidsynth.3.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libfreetype.6.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libglib-2.0.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libgme.0.6.3.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libgme.0.dylib:            Mach-O 64-bit dynamically linked shared library arm64
libgraphite2.3.2.1.dylib:  Mach-O 64-bit dynamically linked shared library arm64
libgraphite2.3.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libgthread-2.0.0.dylib:    Mach-O 64-bit dynamically linked shared library arm64
libharfbuzz.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libintl.8.dylib:           Mach-O 64-bit dynamically linked shared library arm64
libjpeg.8.3.2.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libjpeg.8.dylib:           Mach-O 64-bit dynamically linked shared library arm64
liblua.dylib:              Mach-O 64-bit dynamically linked shared library arm64
libmp3lame.0.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libmpg123.0.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libogg.0.8.5.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libogg.0.dylib:            Mach-O 64-bit dynamically linked shared library arm64
libopus.0.dylib:           Mach-O 64-bit dynamically linked shared library arm64
libopusfile.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libpcre2-8.0.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libpng16.16.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libportaudio.2.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libreadline.8.2.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libreadline.8.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libsndfile.1.0.37.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libsndfile.1.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libvorbis.0.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libvorbisenc.2.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libvorbisfile.3.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libwavpack.1.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libxmp.4.dylib:            Mach-O 64-bit dynamically linked shared library arm64
```
After:
```
libFLAC.12.dylib:          Mach-O 64-bit dynamically linked shared library arm64
libGL.1.dylib:             Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libGL.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libGL.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libGL.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libGLU.1.dylib:            Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386] [arm64]
libGLU.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libGLU.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libGLU.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libSDL2-2.0.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libSDL2_mixer-2.0.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
libSDL2_net-2.0.0.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libSDL2_ttf-2.0.0.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libX11-xcb.1.dylib:        Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libX11-xcb.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libX11-xcb.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libX11-xcb.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libX11.6.dylib:            Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64] [arm64]
libX11.6.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libX11.6.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libX11.6.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libXau.6.dylib:            Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libXau.6.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libXau.6.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libXau.6.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libXext.6.dylib:           Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libXext.6.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libXext.6.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libXext.6.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libfluidsynth.3.3.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
libfluidsynth.3.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libfreetype.6.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libglapi.0.dylib:          Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libglapi.0.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libglapi.0.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libglapi.0.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libglib-2.0.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libgme.0.6.3.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libgme.0.dylib:            Mach-O 64-bit dynamically linked shared library arm64
libgraphite2.3.2.1.dylib:  Mach-O 64-bit dynamically linked shared library arm64
libgraphite2.3.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libgthread-2.0.0.dylib:    Mach-O 64-bit dynamically linked shared library arm64
libharfbuzz.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libintl.8.dylib:           Mach-O 64-bit dynamically linked shared library arm64
libjpeg.8.3.2.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libjpeg.8.dylib:           Mach-O 64-bit dynamically linked shared library arm64
liblua.dylib:              Mach-O 64-bit dynamically linked shared library arm64
libmp3lame.0.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libmpg123.0.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libogg.0.8.5.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libogg.0.dylib:            Mach-O 64-bit dynamically linked shared library arm64
libopus.0.dylib:           Mach-O 64-bit dynamically linked shared library arm64
libopusfile.0.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libpcre2-8.0.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libpng16.16.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libportaudio.2.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libreadline.8.2.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libreadline.8.dylib:       Mach-O 64-bit dynamically linked shared library arm64
libsndfile.1.0.37.dylib:   Mach-O 64-bit dynamically linked shared library arm64
libsndfile.1.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libvorbis.0.dylib:         Mach-O 64-bit dynamically linked shared library arm64
libvorbisenc.2.dylib:      Mach-O 64-bit dynamically linked shared library arm64
libvorbisfile.3.dylib:     Mach-O 64-bit dynamically linked shared library arm64
libwavpack.1.dylib:        Mach-O 64-bit dynamically linked shared library arm64
libxcb-glx.0.dylib:        Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libxcb-glx.0.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libxcb-glx.0.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libxcb-glx.0.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libxcb.1.dylib:            Mach-O universal binary with 3 architectures: [i386:Mach-O dynamically linked shared library i386] [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
libxcb.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
libxcb.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libxcb.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
libxmp.4.dylib:            Mach-O 64-bit dynamically linked shared library arm64
```

Also, cmake is detecting different paths for GL and GLU.

**Comment by nikekson** [comment]
@caco-underscore Does it work if you build with `-DCMAKE_OSX_ARCHITECTURES=arm64`?

**Comment by caco-underscore** [comment]
The result is the same

**Comment by nikekson** [comment]
Did you check what caused the segfault? When I tested the patch on x86_64, I didn't encounter any issues.
I'm pretty lost on why CMake is now picking up non-arm64 libs, and I can't troubleshoot this much further as I don't have access to Apple silicon.

Anyhow, would you mind verifying that #195 works?

**Comment by caco-underscore** [comment]
Hi. Just tested #195; cmake is confused again with Mono libs. At ```cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MACOS_BUNDLE=ON ..```:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find PNG: Found unsuitable version "1.4.12", but required is at
  least "1.6" (found /opt/homebrew/lib/libpng.dylib)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.31/Modules/FindPNG.cmake:180 (find_package_handle_standard_args)
  src/CMakeLists.txt:42 (find_package)
```
CMake is also mixing Mono and homebrew in Intl, JPEG, and SQLITE3.

Haven't checked the cause of the segfault with #194; I thought, there's no point in debugging the segfault without a sane build regarding libs and linking.

**Comment by nikekson** [comment]
Does 637b0a53f97b071d28d7de4cff204c213285ea24 work?

**Comment by caco-underscore** [comment]
Yes; compiles, launch and plays fine. Also, there are no mixed arch libraries anymore. Although, cmake still mixes Mono and homebrew on Intl, JPEG, and SQLITE3; maybe it can give problems in the future. But for now, compiles fine

**Comment by nikekson** [comment]
If the same issue occurs with other libraries, I may end up writing a wrapper macro that makes it easier to specify which dependencies should be discovered through pkg-config, although that might make the CMake spaghetti even worse. But I think it would make more sense than using pkg-config for everything.

**Pull request merged**
